language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer self-update
  - '[ "$TRAVIS_PHP_VERSION" != "7.0" ] || echo "xdebug.overload_var_dump = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'

install:
  - composer install

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
